language: cpp
compiler:
  - gcc
  
before_script:
  # We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - curl -O https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  - unzip gmock-1.7.0.zip
  - mkdir _build
  - cd _build
  - sudo apt-get update -qq
  #- sudo apt-get install libboost-dev libboost-date-time-dev libboost-program-options-dev google-mock gcc-4.9 g++-4.9
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  
script:
  if [ ${COVERITY_SCAN_BRANCH} == 1 ]; then exit ; fi &&
  cmake .. -DCMAKE_BUILD_TYPE=Debug -D=BUILD_TESTS=Yes -DGMOCK_DIR=../gmock-1.7.0 &&
  make -j `nproc` &&
  Test/Tester

